"""Add embedding column

Revision ID: f1add27f7050
Revises: a8e7e2a321cd
Create Date: 2025-02-09 12:34:07.396585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'f1add27f7050'
down_revision: Union[str, None] = 'a8e7e2a321cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('embedding', Vector(1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'embedding')
    # ### end Alembic commands ###
